export enum PermissionEnum {
  MANAGE_USERS = 'MANAGE_USERS',
  VIEW_DASHBOARD = 'VIEW_DASHBOARD',
    VIEW_INCIDENTS = 'VIEW_INCIDENTS',
    MANAGE_SETTINGS = 'MANAGE_SETTINGS',
    CREATE_INCIDENTS = 'CREATE_INCIDENTS',
  }
  