export enum PermissionEnum {
    VIEW_DASHBOARD = 'VIEW_DASHBOARD',
    MANAGE_USERS = 'MANAGE_USERS',
    VIEW_INCIDENTS = 'VIEW_INCIDENTS',
    MANAGE_SETTINGS = 'MANAGE_SETTINGS',
    CREATE_INCIDENTS = 'CREATE_INCIDENTS',
  }
  