// codeToEnumKeyMap.ts
export const codeToEnumKeyMap: { [code: string]: string } = {
    // ILDC - Interest, Leases and Dividend component
    '0030': 'INTEREST_INCOME',
    '0040': 'INTEREST_INCOME',
    '0050': 'INCOME_FROM_LEASED_ASSETS',
    '0060': 'PROFITS_FROM_LEASED_ASSETS',
    '0070': 'INTEREST_EXPENSES',
    '0080': 'INTEREST_EXPENSES',
    '0090': 'EXPENSES_FROM_LEASED_ASSETS',
    '0100': 'LOSSES_FROM_LEASED_ASSETS',
    '0130': 'CASH_BALANCES',
    '0140': 'DEBT_SECURITIES',
    '0150': 'LOANS_AND_ADVANCES',
    '0160': 'DERIVATIVES',
    '0170': 'TRADING_BOOK_HEDGE',
    '0180': 'BANKING_BOOK_HEDGE',
    '0190': 'ASSETS_SUBJECT_TO_LEASES',
    '0200': 'DIVIDEND_INCOME',
    '0210': 'DIVIDEND_INCOME',

    // FC - Financial Component
    '0370': 'TRADING_BOOK_PROFIT',
    '0420': 'BANKING_BOOK_DERECOGNITION',

    // SC - Services Component
    '0220': 'OTHER_OPERATING_INCOME',
    '0230': 'OTHER_OPERATING_INCOME_IPS',
    '0240': 'PROFIT_NON_CURRENT_ASSETS',
    '0250': 'OTHER_OPERATING_INCOME_OTHER', // si distinct
    '0260': 'OTHER_OPERATING_EXPENSES',
    '0270': 'OTHER_OPERATING_EXPENSES_IPS',
    '0280': 'LOSSES_FROM_OPERATIONAL_RISK',
    '0290': 'LOSSES_NON_CURRENT_ASSETS',
    '0300': 'OTHER_EXPENSES',
    '0310': 'FEE_COMMISSION_INCOME',
    '0320': 'FEE_COMMISSION_INCOME', // duplication volontaire si même enum
    '0330': 'FEE_COMMISSION_INCOME_IPS', // si séparé
    '0340': 'FEE_COMMISSION_EXPENSES',
    '0350': 'FEE_COMMISSION_EXPENSES',
    '0360': 'FEE_COMMISSION_EXPENSES_IPS'
};
